### ISSUE TITLE
Add griefing mechanism 

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/lock-app#32]
From keybase talk:

@lkngtn :  what do you think about adding a grieffing parameter to the lock app, so the amount required to lock increases from the configured amount based on a factor based on the number of existing locks the user has?
Would make the locking mechanism more effective as an anti-spam deterrent
since the opportunity cost would increase the more actions you and perform in a given period of time
eg, for the first lock it is 10 tokens for 10 days, for the second its 20 tokens for 20 days, for the third its 30 tokens for 30 days.

The changes i envision contract wise would be on the `forwardFee()` function which would get the user's total current locks and based on this number get the amount required to lock.
Would be something like `currentLocks * lockAmount` where `lockAmount` is the base amount to lock.

We would also have to implement the same logic in the `forward()` function which stores the new lock. Not entirely sure if this could cause an OOG if the user has too many locks. 
Input from @willjgriff would be awesome.

Also what could happen is:

Say a user has 1 current lock for 10 tokens, If it unlocks in the time period he tries to make an intent which will require to create a new lock, the `forwardFee()` and `forward()` function could end getting different `currentLocks` value, 1 and 0 respectively. 
So when the `Aragon client` prompts the user for an approval it will do so for 20 tokens but only 10 will be locked and the lock contract will have an allowance for extra 10.

The time period i'm referring is when the prompt for the approval shows and the user takes say around 3 seconds to confirm the approval.

It's an edge case but worth considering.

**Comment by willjgriff** [comment]
Maybe I'm missing something but as it stands can't a user just use a different account to avoid this restriction?

The only alternative that I think would make it possible would be to add a permission to the `forward`/`lock` function, give the permission for it to a TokenManager, and modify the function so it accepts a `sig` and `msgHash` like in redemptions to use instead of `msg.sender`. The TokenManager isn't likely to dole out tokens so you could be fairly sure each account represents one user. 

However, this ties that implementation to the use of the TokenManager and requires modifying the `forward` functions arguments which I doubt is possible without some Aragon client changes.

**Comment by lkngtn** [comment]
> Maybe I'm missing something but as it stands can't a user just use a different account to avoid this restriction? 

Great point! 

> The only alternative that I think would make it possible would be to add a permission to the forward/lock function, give the permission for it to a TokenManager, and modify the function so it accepts a sig and msgHash like in redemptions to use instead of msg.sender. The TokenManager isn't likely to dole out tokens so you could be fairly sure each account represents one user.

Rather than use the token manager as a forwarder, could we create a simple ACL oracle based that checks token balance, then use that? Thus avoiding the issues with msg.sender validation and forwarder chains?

**Comment by fabriziovigevani** [comment]
> Maybe I'm missing something but as it stands can't a user just use a different account to avoid this restriction?

Ahh, didn't see that one!

> Rather than use the token manager as a forwarder, could we create a simple ACL oracle that checks token balance, then use that? Thus avoiding the issues with msg.sender validation and forwarder chains?

Maybe it could be done without an Oracle, using just `canFroward` function?

**Comment by lkngtn** [comment]
> Maybe it could be done without an Oracle, just using canForward function? 

The nice thing about using the oracle mechanism rather than using canForward is that it leaves the lock app un-opinionated about the types of restrictions put on forwarding. So if someone creates a groups app that is not based on a standard token interface, the group app can provide an oracle interface that could be used instead. 

Besides the fact that oracles don't have great support in the UI, they feel like the more flexible solution. 

> Sounds a bit of an anti pattern as we are not fully leveraging the forwarding mechanism Aragon supplies and it requires to have a reference to the token manager but i think it's better than messing with the client.

Ive been thinking about this quite a bit as we start actually implementing ACL oracles and how the two permission approaches actually interact. I think we are definitely pioneering things here a bit, but I think forwarders make more sense in cases where the action will be processed in some way (eg require tokens to be sent, or require a vote to pass, or some time to elapse), where oracles are better option for in-time validation (does this user have tokens, have they voted yes within some timeframe, etc). I think the actual anti-pattern has been using the token manager as a way to restrict actions to token holders (as opposed to using an oracle for this purpose). 

So creating this restriction as an oracle rather than adding to the canForward function of lock app, means that many cases that are currently using the token manager as a forwarder can instead use the oracle. (This will have a nice side effect in cases like voting, where currently if you restrict creating votes to token holders, the creator of the vote is the token manager and not the actual person which is not very intuitive).

**Comment by willjgriff** [comment]
> > Maybe I'm missing something but as it stands can't a user just use a different account to avoid this restriction?
> 
> Great point!
> 
> > The only alternative that I think would make it possible would be to add a permission to the forward/lock function, give the permission for it to a TokenManager, and modify the function so it accepts a sig and msgHash like in redemptions to use instead of msg.sender. The TokenManager isn't likely to dole out tokens so you could be fairly sure each account represents one user.
> 
> Rather than use the token manager as a forwarder, could we create a simple ACL oracle that checks token balance, then use that? Thus avoiding the issues with msg.sender validation and forwarder chains?

**Comment by willjgriff** [comment]
> Rather than use the token manager as a forwarder, could we create a simple ACL oracle that checks token balance, then use that? Thus avoiding the issues with msg.sender validation and forwarder chains?

This is brilliant. The Lock contract would then require an ACL Oracle (probably a TokenManager Oracle) in order for the griefing mechanism to work, but I think that's reasonable.

**Comment by lkngtn** [comment]
> This is brilliant. The Lock contract would then require an ACL Oracle (probably a TokenManager Oracle) in order for the griefing mechanism to work, but I think that's reasonable. 

I wouldn't say its strictly necessary, because its kind of a pain for normal users to move their tokens from account to account, so if you think of it as a deterrent for proposal spam I think it would be fine without the oracle (or like in a case where you have transferrable tokens). But definitely would be good to be able to have a solution that isnt easily avoided.

Also agree, digging the oracles a lot. I think our use of them will be pretty eye open in terms of showcasing the flexbility of the Aragon Framework which is cool. 👍

**Comment by fabriziovigevani** [comment]
Having a talk with @0xGabi  yesterday, were thinking what would be the best course of action regarding approval of tokens. Majority of dapps today prompts you for an approval for a nearly infinite amount of tokens so that you don't have to approve every time you perform a transaction which requires one. 

This saves user's costs but could create an opportunity for a malicious actor discovering a bug to wipe out your funds, so i think it's best to require the approval every time. 

Also as we are implementing the griefing mechanism i think it's a better solution for transparency where the user knows how much will be locking.

> Say a user has 1 current lock for 10 tokens, If it unlocks in the time period he tries to make an intent which will require to create a new lock, the forwardFee() and forward() function could end getting different currentLocks value, 1 and 0 respectively.
So when the Aragon client prompts the user for an approval it will do so for 20 tokens but only 10 will be locked and the lock contract will have an allowance for extra 10.

I also wanted to discuss what do you think about this cases. I think it's not that uncommon to happen as in rinkeby/mainnet transactions take longer. 

What i came up with is to check in the `forward` function for the token allowance the contract has by the `msg.sender` and lock that amount instead of the one calculated based on the current active locks.

What do you guys think?

**Comment by fabriziovigevani** [comment]
closed by #33
